# Generated by Django 3.2.8 on 2023-01-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('room_name', models.CharField(max_length=300)),
            ],
        ),
    ]
